nfl_team_map = {
    "ARI": "Arizona Cardinals",
    "ATL": "Atlanta Falcons",
    "BAL": "Baltimore Ravens",
    "BUF": "Buffalo Bills",
    "CAR": "Carolina Panthers",
    "CHI": "Chicago Bears",
    "CIN": "Cincinnati Bengals",
    "CLE": "Cleveland Browns",
    "DAL": "Dallas Cowboys",
    "DEN": "Denver Broncos",
    "DET": "Detroit Lions",
    "GB": "Green Bay Packers",
    "HOU": "Houston Texans",
    "IND": "Indianapolis Colts",
    "JAX": "Jacksonville Jaguars",
    "KC": "Kansas City Chiefs",
    "LV": "Las Vegas Raiders",
    "LAC": "Los Angeles Chargers",
    "LAR": "Los Angeles Rams",
    "MIA": "Miami Dolphins",
    "MIN": "Minnesota Vikings",
    "NE": "New England Patriots",
    "NO": "New Orleans Saints",
    "NYG": "New York Giants",
    "NYJ": "New York Jets",
    "PHI": "Philadelphia Eagles",
    "PIT": "Pittsburgh Steelers",
    "PITT": "Pittsburgh Steelers",
    "SF": "San Francisco 49ers",
    "SEA": "Seattle Seahawks",
    "TB": "Tampa Bay Buccaneers",
    "TEN": "Tennessee Titans",
    "WAS": "Washington Commanders"
}

ncaa_team_map = {
    "ALA": "Alabama Crimson Tide",
    "ARK": "Arkansas Razorbacks",
    "AUB": "Auburn Tigers",
    "UGA": "Georgia Bulldogs",
    "UK": "Kentucky Wildcats",
    "LSU": "LSU Tigers",
    "MISS": "Ole Miss Rebels",
    "MSST": "Mississippi State Bulldogs",
    "MIZ": "Missouri Tigers",
    "SCAR": "South Carolina Gamecocks",
    "TAMU": "Texas A&M Aggies",
    "UF": "Florida Gators",
    "TEN": "Tennessee Volunteers",
    "VAN": "Vanderbilt Commodores",

    "CLEM": "Clemson Tigers",
    "DUKE": "Duke Blue Devils",
    "FSU": "Florida State Seminoles",
    "LOU": "Louisville Cardinals",
    "MIA": "Miami Hurricanes",
    "NCST": "NC State Wolfpack",
    "UNC": "North Carolina Tar Heels",
    "UVA": "Virginia Cavaliers",
    "VT": "Virginia Tech Hokies",
    "WAKE": "Wake Forest Demon Deacons",
    "BC": "Boston College Eagles",
    "SYR": "Syracuse Orange",
    "PITT": "Pittsburgh Panthers",

    "OU": "Oklahoma Sooners",
    "TEX": "Texas Longhorns",
    "TTU": "Texas Tech Red Raiders",
    "TCU": "TCU Horned Frogs",
    "OKST": "Oklahoma State Cowboys",
    "KU": "Kansas Jayhawks",
    "KSU": "Kansas State Wildcats",
    "WVU": "West Virginia Mountaineers",
    "BYU": "BYU Cougars",
    "HOU": "Houston Cougars",
    "UCF": "UCF Knights",
    "CIN": "Cincinnati Bearcats",

    "OSU": "Ohio State Buckeyes",
    "MICH": "Michigan Wolverines",
    "MSU": "Michigan State Spartans",
    "PSU": "Penn State Nittany Lions",
    "IOWA": "Iowa Hawkeyes",
    "WIS": "Wisconsin Badgers",
    "MINN": "Minnesota Golden Gophers",
    "NEB": "Nebraska Cornhuskers",
    "ILL": "Illinois Fighting Illini",
    "NW": "Northwestern Wildcats",
    "PUR": "Purdue Boilermakers",
    "IND": "Indiana Hoosiers",
    "MD": "Maryland Terrapins",
    "RUTG": "Rutgers Scarlet Knights",

    "ND": "Notre Dame Fighting Irish",

    "USC": "USC Trojans",
    "UCLA": "UCLA Bruins",
    "WASH": "Washington Huskies",
    "WSU": "Washington State Cougars",
    "ORE": "Oregon Ducks",
    "ORST": "Oregon State Beavers",
    "STAN": "Stanford Cardinal",
    "CAL": "California Golden Bears",
    "COLO": "Colorado Buffaloes",
    "UTAH": "Utah Utes",
    "ASU": "Arizona State Sun Devils",
    "ARIZ": "Arizona Wildcats",

    "BSU": "Boise State Broncos",
    "SDSU": "San Diego State Aztecs",
    "FRES": "Fresno State Bulldogs",
    "UNLV": "UNLV Rebels",
    "NEV": "Nevada Wolf Pack",
    "HAW": "Hawai'i Rainbow Warriors",
    "SJSU": "San Jose State Spartans",
    "CSU": "Colorado State Rams",
    "WYO": "Wyoming Cowboys",
    "AF": "Air Force Falcons",
    "UNM": "New Mexico Lobos",
    "UTST": "Utah State Aggies",

    "UCONN": "UConn Huskies",
    "UMASS": "UMass Minutemen",
    "ARMY": "Army Black Knights",
    "NAVY": "Navy Midshipmen",

    # AAC / Sun Belt / C-USA / MAC / etc.
    "ECU": "East Carolina Pirates",
    "TUL": "Tulane Green Wave",
    "TLSA": "Tulsa Golden Hurricane",
    "SMU": "SMU Mustangs",
    "MEM": "Memphis Tigers",
    "TEM": "Temple Owls",
    "USF": "South Florida Bulls",

    "APP": "Appalachian State Mountaineers",
    "GASO": "Georgia Southern Eagles",
    "GSU": "Georgia State Panthers",
    "TROY": "Troy Trojans",
    "USA": "South Alabama Jaguars",
    "ODU": "Old Dominion Monarchs",
    "COAST": "Coastal Carolina Chanticleers",
    "ARST": "Arkansas State Red Wolves",
    "ULM": "ULM Warhawks",
    "ULL": "Louisiana Ragin’ Cajuns",

    "UNT": "North Texas Mean Green",
    "UTSA": "UTSA Roadrunners",
    "RICE": "Rice Owls",
    "UAB": "UAB Blazers",
    "FAU": "Florida Atlantic Owls",
    "FIU": "FIU Panthers",
    "MTSU": "Middle Tennessee Blue Raiders",
    "WKU": "Western Kentucky Hilltoppers",
    "CHAR": "Charlotte 49ers",

    "AKR": "Akron Zips",
    "BALL": "Ball State Cardinals",
    "BGSU": "Bowling Green Falcons",
    "BUFF": "Buffalo Bulls",
    "CMU": "Central Michigan Chippewas",
    "EMU": "Eastern Michigan Eagles",
    "KENT": "Kent State Golden Flashes",
    "MIAOH": "Miami (OH) RedHawks",
    "NIU": "Northern Illinois Huskies",
    "OHIO": "Ohio Bobcats",
    "TOL": "Toledo Rockets",
    "WMU": "Western Michigan Broncos"
}
